json.extract! business,
            :id,
            :name,
            :address,
            :city,
            :state,
            :b_zip_code,
            :phone_num,
            :website,
            :price_range,
            :latitude,
            :longitude,
            :categories,
            :delivery,
            :takeout,
            :outdoor